### ISSUE TITLE
Absolutely does NOT work for me at all with SR6 with any software I have tried when set to V3 mode.

### ISSUE THREAD

**Issue by geogan** [jcfain/TCodeESP32#6]
I have discussed this before, but no idea what the hell is going on. 

I have noting out of the ordinary hardware wise. Use same ESP32 dev kit as everyone.

But I absolutely HAVE to keep this firmware on the V2 mode.

I tried again today to see if I could use the V3 mode (from admin page at http://tcode.local/) and it does as it always does - the SR6 goes absolutely haywire when any motion is sent to it. Tried MOSA and latest MultiFunPlayer (set to TCode-0.3 in its settings) - they both do same thing. As soon as motion is started the SR6 jerks, chucks, does not follow motion, appears to be damaging the servos.

Both these programs ONLY work for me when firmware is set to V2 mode.

No idea what's going on.

Using ESP32 v0.23b right now.

**Comment by jcfain** [comment]
This issue was resolved in v0.25 correct?
